<a href="https://colab.research.google.com/github/nevesle/Learning-Python/blob/main/Numpy%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Speed.    It is faster because it is built on C

In [1]:
import time 
import numpy as np

In [ ]:
x = np.random.random(1000000000)

In [ ]:
start = time.time()
sum(x)/len(x)                # Normal Python Mean
print(time.time()-start)

0.012563228607177734


In [ ]:
start = time.time()
np.mean(x)                    # Numpy Mean
print(time.time()-start)

0.00138092041015625


2. N dimensional arrays. e.g Matrices 

3. Mathematical functions

In [2]:
#1d arrays 
py_list = [1,23,4,5,6,7,8]
array = np.array(py_list)
array

array([ 1, 23,  4,  5,  6,  7,  8])

In [3]:
#2d array
py_list2 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(py_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.random.random((3,3))

array([[0.05493202, 0.49543772, 0.72486219],
       [0.88200519, 0.8892448 , 0.80547197],
       [0.85114312, 0.74123484, 0.39414982]])

In [15]:
np.arange(1.51, 1.6)

array([1.51])

In [17]:
#3d arrays 
array_1 = np.array([[1,2],[2,3]])
array_2 = np.array([[1,2],[2,3]])
array_3 = np.array([[1,2],[2,3]])

array_3d = np.array([array_1, array_2,array_1])
array_3d.shape

(3, 2, 2)

In [18]:
array_3.flatten()

array([1, 2, 2, 3])

In [21]:
array_3d.reshape((2,3,2))

array([[[1, 2],
        [2, 3],
        [1, 2]],

       [[2, 3],
        [1, 2],
        [2, 3]]])

In [23]:
int_32_array = np.array([1,2,3,4,5], dtype = np.int32)
int_64_array = np.array([1,2,3,4,5], dtype = np.int64)
float_32_array = np.array([1,2,3,4,5], dtype = np.float32)
float_64_array = np.array([1,2,3,4,5], dtype = np.float64)

print(int_32_array.dtype)
print(int_64_array.dtype)
print(float_32_array.dtype)
float_64_array.dtype

int32
int64
float32


dtype('float64')